CREATE DATABASE IF NOT EXISTS bd_clientes;
CREATE DATABASE IF NOT EXISTS bd_empleados;
CREATE DATABASE IF NOT EXISTS bd_productos;
CREATE DATABASE IF NOT EXISTS bd_sucursales;
CREATE DATABASE IF NOT EXISTS bd_pedidos;
CREATE DATABASE IF NOT EXISTS bd_envios;
CREATE DATABASE IF NOT EXISTS bd_inventarios;
CREATE DATABASE IF NOT EXISTS bd_boletas;
